# Generated by Django 2.1.3 on 2018-11-02 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('viewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
