# Generated by Django 2.1.3 on 2018-11-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteme', '0003_auto_20181102_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='viewed_at',
        ),
    ]
