# Generated by Django 2.1.3 on 2018-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteme', '0004_auto_20181102_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
